spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          search-paths: src/main/resources/config
          default-label: main
          uri: https://github.com/mofe64/EagleEye-ConfigServer
          username: mofe64
          password:
          skipSslValidation: true

server:
  port: 8071