spring:
  application:
    name: config-server
  profiles:
    active: native, git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/mofe64/EagleEye-ConfigServer.git
          search-paths: licensing-service
server:
  port: 8071